// Single content source (generated by scripts/migrate_content.py from DeanFi2's content.json +
// data.ts overrides). Facts only: see REVAMP-HANDOFF.md for what must not be invented.
import data from './portfolio.json';

export type Project = (typeof data.projects)[number];
export type SpeakingEvent = (typeof data.events)[number];

export const projects: Project[] = data.projects;
export const events: SpeakingEvent[] = data.events;

export const countries: Record<string, string> = { CN: 'China', ID: 'Indonesia', MY: 'Malaysia' };

export type ToolId = 'figma' | 'photoshop' | 'gemini' | 'claude' | 'codex';
export const toolNames: Record<ToolId, string> = {
  figma: 'Figma',
  photoshop: 'Photoshop',
  gemini: 'Gemini',
  claude: 'Claude',
  codex: 'Codex',
};
export const toolLogo = (id: string) => `/media/tool-logos/${id}.svg`;

export const profile = {
  name: 'Dean',
  studio: 'Dean Studio',
  roles: ['UI/UX Designer', 'Frontend Developer', 'Creative Designer'],
  // Existing copy from DeanFi2 (AboutObservatory.tsx), unchanged.
  bio: [
    'I turn complex Web3 ideas into interfaces people can understand and enjoy. My work spans high-fidelity landing pages and the frontend code that brings them to life.',
    'Beyond the screen, I present projects, lead conversations, and share what I’ve learned with the Web3 community in English and conversational Mandarin.',
  ],
  toolGroups: [
    { title: 'Web Design & Creative', tools: ['figma', 'photoshop'] as ToolId[] },
    { title: 'Web Development & Creative', tools: ['gemini', 'claude', 'codex'] as ToolId[] },
  ],
  // Flags are a visual cue only (not nationality, not proficiency).
  languages: [
    { name: 'English', flag: '/media/flags/gb.svg' },
    { name: 'Mandarin', flag: '/media/flags/cn.svg' },
    { name: 'Bahasa Melayu', flag: '/media/flags/my.svg' },
  ],
  portrait: { color: '/media/dean-portrait.webp', eink: '/media/dean-portrait-eink.png' },
} as const;
